---
deployment:
  tasks:
    - /bin/bash -lc "npm ci"
    - /bin/bash -lc "npm run build"
    - /bin/bash -lc "rm -rf ~/public_html/app"
    - /bin/bash -lc "mkdir -p ~/public_html/app"
    - /bin/bash -lc "rsync -av --delete dist/ ~/public_html/app/"
